[build]
  base = "todo"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://todo-me8t.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 